# Generated by Django 4.2.2 on 2023-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="discription",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
