# Generated by Django 4.2.2 on 2023-06-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_todo_discription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="discription",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="createdDate",
        ),
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
