# Generated by Django 4.2.2 on 2023-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_discription_todo_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="userName",
            new_name="user_name",
        ),
        migrations.AddField(
            model_name="todo",
            name="file",
            field=models.FileField(
                default=None, max_length=150, null=True, upload_to="files/"
            ),
        ),
    ]
